server:
  servlet:
    context-path: /api

#app:
#  jdbc-url: jdbc:mysql://localhost:3306/spring_react
#  username: root
#  password: admin
#  poolsize: 30

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/spring_react
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true